# Generated by Django 3.1.2 on 2020-10-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationanswer',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
