# Generated by Django 3.1.2 on 2020-10-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_0739'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcategory',
            name='account_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accountcategory'),
        ),
    ]
