# Generated by Django 3.1.2 on 2020-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationcategory_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
