# Generated by Django 3.1.2 on 2020-10-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.applicationcategory'),
        ),
    ]
