# Generated by Django 3.1.2 on 2020-10-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcategory'),
            preserve_default=False,
        ),
    ]
